package com.dream.application.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "LAW_HEAD_THIRD".
 */
@Entity
public class LawHeadThird {
    private Long id;
    private String secondHeadId;
    private String content;

    @Generated
    public LawHeadThird() {
    }

    @Generated
    public LawHeadThird(Long id, String secondHeadId, String content) {
        this.id = id;
        this.secondHeadId = secondHeadId;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSecondHeadId() {
        return secondHeadId;
    }

    public void setSecondHeadId(String secondHeadId) {
        this.secondHeadId = secondHeadId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
