package com.dream.application.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "LAW_HEAD_SECOND".
 */
@Entity
public class LawHeadSecond {
    private Long id;
    private String headId;
    private String title;

    @Generated
    public LawHeadSecond() {
    }

    @Generated
    public LawHeadSecond(Long id, String headId, String title) {
        this.id = id;
        this.headId = headId;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHeadId() {
        return headId;
    }

    public void setHeadId(String headId) {
        this.headId = headId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
